SELECT A.PROJECTNAME, B.PNLGRPNAME, B.DESCR
FROM PSPROJECTITEM A,
  PSPNLGRPDEFN B
WHERE B.PNLGRPNAME = A.OBJECTVALUE1
AND B.MARKET         = A.OBJECTVALUE2
AND A.OBJECTTYPE     = 7
--AND A.PROJECTNAME = 'XXXXXXXXXXX'
AND NOT EXISTS(SELECT 'X' FROM PSPRSMDEFN C WHERE B.PNLGRPNAME = C.PORTAL_URI_SEG2) 