SELECT * 
FROM PSPNLFIELD A,
  PSPNLFIELDEXT B,
  PSPROJECTITEM C
WHERE  A.PNLNAME = B.PNLNAME
AND A.PNLFLDID    = B.PNLFLDID
AND LBLTYPE = 1
AND B.GRPBOXTYPE <> 5
AND A.LBLTEXT <> ' '
AND A.PNLNAME     = C.OBJECTVALUE1
AND C.OBJECTTYPE  = 5
--AND C.PROJECTNAME = 'XXXXXXXXXXX'