

SELECT DISTINCT OBJECTID1, OBJECTVALUE1, OBJECTID2, OBJECTVALUE2, OBJECTID3, OBJECTVALUE3, OBJECTID4, OBJECTVALUE4, OBJECTID5, OBJECTVALUE5, OBJECTID6, OBJECTVALUE6, OBJECTID7, OBJECTVALUE7 FROM PSPCMNAME WHERE RECNAME= 'SQL' AND REFNAME LIKE 'CY2%'
	
SELECT DISTINCT A.PROJECTNAME, A.OBJECTTYPE, A.OBJECTID1, B.OBJECTID1, A.OBJECTVALUE1, B.OBJECTVALUE1, A.OBJECTID2, B.OBJECTID2, A.OBJECTVALUE2, B.OBJECTVALUE2, A.OBJECTID3, B.OBJECTID3, A.OBJECTVALUE3, B.OBJECTVALUE3, A.OBJECTID4, B.OBJECTID4, A.OBJECTVALUE4, B.OBJECTVALUE4, C.APPCLASSID, C.PACKAGEROOT, C.QUALIFYPATH, d.REFNAME
  FROM PSPROJECTITEM A, PSPCMTXT B, PSAPPCLASSDEFN C, PSPCMNAME D
  WHERE ( A.OBJECTTYPE = 58
     AND A.OBJECTVALUE1 = B.OBJECTVALUE1
     AND A.OBJECTVALUE2 = B.OBJECTVALUE2
     AND ( A.OBJECTVALUE3 = B.OBJECTVALUE3
     OR A.OBJECTVALUE3 = ' ')
     AND ( A.OBJECTVALUE4 = B.OBJECTVALUE4
     OR A.OBJECTVALUE4 = ' ')
     AND B.OBJECTID1 = A.OBJECTID1
     AND B.OBJECTID2 = A.OBJECTID2
     AND ( A.OBJECTID3 = B.OBJECTID3
     OR A.OBJECTID3 = 0)
     AND ( A.OBJECTID4 = B.OBJECTID4
     OR A.OBJECTID4 = 0)
     AND A.OBJECTVALUE1 = C.PACKAGEROOT
     AND C.APPCLASSID = (CASE WHEN  A.OBJECTVALUE4 = ' ' THEN CASE WHEN  A.OBJECTVALUE3 = ' ' THEN  A.OBJECTVALUE2 ELSE   A.OBJECTVALUE3 END ELSE  A.OBJECTVALUE4 END)
     AND C.QUALIFYPATH = (CASE WHEN   A.OBJECTVALUE4 = ' ' THEN CASE WHEN   A.OBJECTVALUE3 = ' ' THEN ':' ELSE   A.OBJECTVALUE2 END ELSE   A.OBJECTVALUE2 ||':'||   A.OBJECTVALUE3 END)
   and  B.OBJECTID1 = D.OBJECTID1  
   AND B.OBJECTVALUE1 = D.OBJECTVALUE1  
   AND B.OBJECTID2 = D.OBJECTID2  
   AND B.OBJECTVALUE2 = D.OBJECTVALUE2  
   AND B.OBJECTID3 = D.OBJECTID3  
   AND B.OBJECTVALUE3 = D.OBJECTVALUE3  
   AND B.OBJECTID4 = D.OBJECTID4  
   AND B.OBJECTVALUE4 = D.OBJECTVALUE4  
   AND B.OBJECTID5 = D.OBJECTID5  
   AND B.OBJECTVALUE5 = D.OBJECTVALUE5  
   AND B.OBJECTID6 = D.OBJECTID6  
   AND B.OBJECTVALUE6 = D.OBJECTVALUE6  
   AND B.OBJECTID7 = D.OBJECTID7  
   AND B.OBJECTVALUE7 = D.OBJECTVALUE7
   AND D.RECNAME= 'SQL'
   AND A.PROJECTNAME = 'CY2_AD_FL_201'
   )
   
   
   
   SELECT DISTINCT d.REFNAME
  FROM PSPROJECTITEM A, PSPCMTXT B, PSAPPCLASSDEFN C, PSPCMNAME D
  WHERE 
  --A.OBJECTTYPE = 58
     --AND
     A.OBJECTVALUE1 = B.OBJECTVALUE1
     AND A.OBJECTVALUE2 = B.OBJECTVALUE2
     AND ( A.OBJECTVALUE3 = B.OBJECTVALUE3
     OR A.OBJECTVALUE3 = ' ')
     AND ( A.OBJECTVALUE4 = B.OBJECTVALUE4
     OR A.OBJECTVALUE4 = ' ')
     AND B.OBJECTID1 = A.OBJECTID1
     AND B.OBJECTID2 = A.OBJECTID2
     AND ( A.OBJECTID3 = B.OBJECTID3
     OR A.OBJECTID3 = 0)
     AND ( A.OBJECTID4 = B.OBJECTID4
     OR A.OBJECTID4 = 0)
     AND A.OBJECTVALUE1 = C.PACKAGEROOT
     AND C.APPCLASSID = (CASE WHEN  A.OBJECTVALUE4 = ' ' THEN CASE WHEN  A.OBJECTVALUE3 = ' ' THEN  A.OBJECTVALUE2 ELSE   A.OBJECTVALUE3 END ELSE  A.OBJECTVALUE4 END)
     AND C.QUALIFYPATH = (CASE WHEN   A.OBJECTVALUE4 = ' ' THEN CASE WHEN   A.OBJECTVALUE3 = ' ' THEN ':' ELSE   A.OBJECTVALUE2 END ELSE   A.OBJECTVALUE2 ||':'||   A.OBJECTVALUE3 END)
   and  B.OBJECTID1 = D.OBJECTID1  
   AND B.OBJECTVALUE1 = D.OBJECTVALUE1  
   AND B.OBJECTID2 = D.OBJECTID2  
   AND B.OBJECTVALUE2 = D.OBJECTVALUE2  
   AND B.OBJECTID3 = D.OBJECTID3  
   AND B.OBJECTVALUE3 = D.OBJECTVALUE3  
   AND B.OBJECTID4 = D.OBJECTID4  
   AND B.OBJECTVALUE4 = D.OBJECTVALUE4  
   AND B.OBJECTID5 = D.OBJECTID5  
   AND B.OBJECTVALUE5 = D.OBJECTVALUE5  
   AND B.OBJECTID6 = D.OBJECTID6  
   AND B.OBJECTVALUE6 = D.OBJECTVALUE6  
   AND B.OBJECTID7 = D.OBJECTID7  
   AND B.OBJECTVALUE7 = D.OBJECTVALUE7
   AND D.RECNAME= 'SQL'
   AND A.PROJECTNAME = 'CY2_AD_FL_201'
   and not exists(SELECT B.PROJECTNAME, A.SQLID, A.SQLTYPE, A.MARKET, A.DBTYPE, TO_CHAR(A.EFFDT,'YYYY-MM-DD'), A.SEQNUM, A.SQLTEXT, CASE WHEN  A.SQLTYPE  = 0 THEN 'Normal' WHEN  A.SQLTYPE  = 1 THEN 'Application Engine' WHEN  A.SQLTYPE = 2 THEN 'Record view' ELSE  A.SQLTYPE END, C.DESCR, C.DESCRLONG
  FROM PSSQLTEXTDEFN A, PSPROJECTITEM B, PSSQLDESCR C
  WHERE A.EFFDT =
        (SELECT MAX(A_ED.EFFDT) FROM PSSQLTEXTDEFN A_ED
        WHERE A.SQLID = A_ED.SQLID
          AND A.SQLTYPE = A_ED.SQLTYPE
          AND A.MARKET = A_ED.MARKET
          AND A.DBTYPE = A_ED.DBTYPE
          AND A_ED.EFFDT <= SYSDATE)
     AND B.OBJECTTYPE = 30
     AND B.OBJECTID1 = 65
     AND B.OBJECTVALUE1 = A.SQLID
     AND A.SQLID = C.SQLID
     AND A.SQLTYPE = C.SQLTYPE
     AND A.MARKET = C.MARKET
     AND A.DBTYPE = C.DBTYPE
     AND C.EFFDT =
        (SELECT MAX(C_ED.EFFDT) FROM PSSQLDESCR C_ED
        WHERE C.SQLID = C_ED.SQLID
          AND C.SQLTYPE = C_ED.SQLTYPE
          AND C.MARKET = C_ED.MARKET
          AND C.DBTYPE = C_ED.DBTYPE
          AND C_ED.EFFDT <= SYSDATE)
          AND B.PROJECTNAME = 'CY2_AD_FL_201'
          and d.REFNAME = A.SQLID)


   
   SELECT DISTINCT d.REFNAME
  FROM PSPROJECTITEM A, PSPCMTXT B
  --, PSAPPCLASSDEFN C
  , PSPCMNAME D
  WHERE A.OBJECTVALUE1 = B.OBJECTVALUE1
     AND A.OBJECTVALUE2 = B.OBJECTVALUE2
     AND ( A.OBJECTVALUE3 = B.OBJECTVALUE3
     OR A.OBJECTVALUE3 = ' ')
     AND ( A.OBJECTVALUE4 = B.OBJECTVALUE4
     OR A.OBJECTVALUE4 = ' ')
     AND B.OBJECTID1 = A.OBJECTID1
     AND B.OBJECTID2 = A.OBJECTID2
     AND ( A.OBJECTID3 = B.OBJECTID3
     OR A.OBJECTID3 = 0)
     AND ( A.OBJECTID4 = B.OBJECTID4
     OR A.OBJECTID4 = 0)
--     AND A.OBJECTVALUE1 = C.PACKAGEROOT
--     AND C.APPCLASSID = (CASE WHEN  A.OBJECTVALUE4 = ' ' THEN CASE WHEN  A.OBJECTVALUE3 = ' ' THEN  A.OBJECTVALUE2 ELSE   A.OBJECTVALUE3 END ELSE  A.OBJECTVALUE4 END)
--  AND C.QUALIFYPATH = (CASE WHEN   A.OBJECTVALUE4 = ' ' THEN CASE WHEN   A.OBJECTVALUE3 = ' ' THEN ':' ELSE   A.OBJECTVALUE2 END ELSE   A.OBJECTVALUE2 ||':'||   A.OBJECTVALUE3 END)
   and  B.OBJECTID1 = D.OBJECTID1  
   AND B.OBJECTVALUE1 = D.OBJECTVALUE1  
   AND B.OBJECTID2 = D.OBJECTID2  
   AND B.OBJECTVALUE2 = D.OBJECTVALUE2  
   AND B.OBJECTID3 = D.OBJECTID3  
   AND B.OBJECTVALUE3 = D.OBJECTVALUE3  
   AND B.OBJECTID4 = D.OBJECTID4  
   AND B.OBJECTVALUE4 = D.OBJECTVALUE4  
   AND B.OBJECTID5 = D.OBJECTID5  
   AND B.OBJECTVALUE5 = D.OBJECTVALUE5  
   AND B.OBJECTID6 = D.OBJECTID6  
   AND B.OBJECTVALUE6 = D.OBJECTVALUE6  
   AND B.OBJECTID7 = D.OBJECTID7  
   AND B.OBJECTVALUE7 = D.OBJECTVALUE7
   AND D.RECNAME= 'SQL'
   AND A.PROJECTNAME = 'CY2_AD_FL_201'
   and not exists(SELECT 