SELECT DISTINCT D.REFNAME
  FROM PSPROJECTITEM A, PSPCMNAME D
  WHERE A.OBJECTVALUE1 = D.OBJECTVALUE1
     AND A.OBJECTVALUE2 = D.OBJECTVALUE2
     AND ( A.OBJECTVALUE3 = D.OBJECTVALUE3
     OR A.OBJECTVALUE3 = ' ')
     AND ( A.OBJECTVALUE4 = D.OBJECTVALUE4
     OR A.OBJECTVALUE4 = ' ')
     AND D.OBJECTID1 = A.OBJECTID1
     AND D.OBJECTID2 = A.OBJECTID2
     AND ( A.OBJECTID3 = D.OBJECTID3
     OR A.OBJECTID3 = 0)
     AND ( A.OBJECTID4 = D.OBJECTID4
     OR A.OBJECTID4 = 0)
   AND D.RECNAME= 'SQL'
   --AND A.PROJECTNAME = 'XXXXXXX'
   and not exists(SELECT 'x' from PSSQLTEXTDEFN E where D.REFNAME = E.SQLID) 
