what can we search for
- missing in project but used
- in project but not used
- missing in project and also not in db



   SELECT distinct B.PROJECTNAME, A.MESSAGE_SET_NBR, A.MESSAGE_NBR, C.OBJECTVALUE1, c.OBJECTVALUE2, c.OBJECTVALUE3, c.OBJECTVALUE4, c.OBJECTVALUE5
  FROM PSMSGCATDEFN A, PSPCMTXT C, PSPROJECTITEM B, PSPCMPROG D
  WHERE  B.OBJECTTYPE = 25
     AND B.OBJECTID1 = 48
     AND B.OBJECTVALUE1 = A.MESSAGE_SET_NBR
     AND B.OBJECTID2 = 49
     AND B.OBJECTVALUE2 = A.MESSAGE_NBR
     AND B.PROJECTNAME = 'CY2_CONFIG_001' 
AND D.OBJECTID1 = C.OBJECTID1 
   AND D.OBJECTVALUE1 = C.OBJECTVALUE1 
   AND D.OBJECTID2 = C.OBJECTID2 
   AND D.OBJECTVALUE2 = C.OBJECTVALUE2 
   AND D.OBJECTID3 = C.OBJECTID3 
   AND D.OBJECTVALUE3 = C.OBJECTVALUE3 
   AND D.OBJECTID4 = C.OBJECTID4 
   AND D.OBJECTVALUE4 = C.OBJECTVALUE4 
   AND D.OBJECTID5 = C.OBJECTID5 
   AND D.OBJECTVALUE5 = C.OBJECTVALUE5 
   AND D.OBJECTID6 = C.OBJECTID6 
   AND D.OBJECTVALUE6 = C.OBJECTVALUE6 
   AND D.OBJECTID7 = C.OBJECTID7 
   AND D.OBJECTVALUE7 = C.OBJECTVALUE7 
   AND D.PROGSEQ = C.PROGSEQ
   AND D.LASTUPDOPRID <> 'PPLSOFT' 
 AND C.PCTEXT LIKE ('%' || A.MESSAGE_SET_NBR || ', ' || A.MESSAGE_NBR || '%');
 
 
 SELECT * 
FROM PSPNLFIELD A,
  PSPNLFIELDEXT B,
  PSPROJECTITEM C
WHERE  A.PNLNAME = B.PNLNAME
AND A.PNLFLDID    = B.PNLFLDID
AND LBLTYPE = 1
AND B.GRPBOXTYPE <> 5
AND A.LBLTEXT <> ' '
AND A.PNLNAME     = C.OBJECTVALUE1
AND C.OBJECTTYPE  = 5
AND C.PROJECTNAME = 'CY2_CONFIG_001' 

/* USE TO CHECK MESSAGE CATALOG ENTRIES */ 
select * from PSPNLBTNDATA WHERE PNLNAME LIKE 'CY2%'

 SELECT c.projectname, A.PNLNAME, A.GRDLBLMSGSET, A.GRDLBLMSGnum
  FROM PSPNLFIELD A, PSPNLDEFN B, PSPROJECTITEM C
  WHERE  A.PNLNAME = B.PNLNAME
     AND A.PNLNAME = C.OBJECTVALUE1
     AND C.OBJECTTYPE = 5
      AND C.PROJECTNAME = 'CY2_CONFIG_001'
  AND A.GRDLBLMSGSET > 0;
  
  
  SELECT * FROM SYSADM.psdbfldlabl where fieldname like 'CY2%' and label_id <> fieldname
SELECT * FROM SYSADM.PSDBFLDLABLLANG  where fieldname like 'CY2%' and label_id <> fieldnamea

     /* records in the project that are not in the database */
      SELECT DISTINCT A.PROJECTNAME, A.OBJECTVALUE1
  FROM PSPROJECTITEM A
  WHERE  A.OBJECTTYPE = 0
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' FROM psrecdefn B WHERE B.RECNAME = A.OBJECTVALUE1);
     
         /* FIELDS IN THE PROJECT THAT ARE NOT IN THE DATABASE */
     SELECT A.PROJECTNAME, A.OBJECTVALUE1
  FROM PSPROJECTITEM A
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
   AND NOT EXISTS(SELECT 'X' FROM PSDBFIELD B WHERE B.FIELDNAME = A.OBJECTVALUE1);

/* Fluid style classes for page fields */
select A.PNLNAME, A.RECNAME, A.FIELDNAME, A.FIELDNUM, B.ffstylelong  from pspnlfielD A
, pspnlfieldEXT B WHERE B.ffstylelong not like ' | | | | ' AND B.ffstylelong not like ' '
AND A.PNLNAME = B.PNLNAME 
AND A.PNLFLDID = B.PNLFLDID
AND EXISTS(
SELECT 'X' FROM 
PSPROJECTITEM C
  WHERE  C.OBJECTTYPE = 5
     AND A.PNLNAME = C.OBJECTVALUE1
        AND C.PROJECTNAME = 'CY2_CONFIG_001');
        
        
/* Fluid style classes for pages */
select A.PNLNAME, A.FFSTYLEDESKTOP, A.FFSTYLEPHONE, A.FFSTYLETABLET, A.FFSTYLEMEDIUM, A.FFSTYLEEXLARGE 
from PSPNLDEFN A WHERE 
(A.FFSTYLEDESKTOP <> ' ' OR 
A.FFSTYLEPHONE  <> ' ' OR A.FFSTYLETABLET  <> ' ' OR A.FFSTYLEMEDIUM  <> ' ' OR  A.FFSTYLEEXLARGE  <> ' ')
AND EXISTS(
SELECT 'X' FROM 
PSPROJECTITEM B
  WHERE  B.OBJECTTYPE = 5
     AND A.PNLNAME = B.OBJECTVALUE1
        AND B.PROJECTNAME = 'CY2_CONFIG_001');

/* page peoplecodes without matching page in project */
SELECT A.PROJECTNAME, C.PNLNAME, B.PCTEXT
  FROM PSPROJECTITEM A, PSPCMTXT B,  PSPNLDEFN C
  WHERE A.OBJECTTYPE = 44
     AND A.OBJECTVALUE1 = B.OBJECTVALUE1
     AND A.OBJECTVALUE2 = B.OBJECTVALUE2
     AND B.OBJECTID1 = A.OBJECTID1
     AND B.OBJECTID2 = A.OBJECTID2
     AND B.OBJECTVALUE1 = C.PNLNAME
     AND A.PROJECTNAME LIKE 'CY2_CONFIG_001'
     AND NOT EXISTS(SELECT 'X'
  FROM PSPROJECTITEM D, PSPNLDEFN E
  WHERE D.OBJECTTYPE = 5
     AND E.PNLNAME = D.OBJECTVALUE1
     AND E.PNLNAME = C.PNLNAME
    AND D.PROJECTNAME =  A.PROJECTNAME);
           
/* pages with missing page peoplecode in project */
SELECT A.PROJECTNAME, B.PNLNAME, C.PCTEXT
FROM PSPROJECTITEM A, PSPNLDEFN B, PSPCMTXT C
  WHERE  A.OBJECTTYPE = 5
     AND B.PNLNAME = A.OBJECTVALUE1
     AND B.PNLNAME = C.OBJECTVALUE1
     AND C.OBJECTID1 = 9
        AND A.PROJECTNAME LIKE 'CY2_CONFIG_001'
  AND NOT EXISTS(SELECT 'X'
  FROM PSPROJECTITEM D, PSPCMTXT E
  WHERE D.OBJECTTYPE = 44
     AND D.OBJECTVALUE1 = E.OBJECTVALUE1
     AND D.OBJECTVALUE2 = E.OBJECTVALUE2
     AND D.OBJECTID1 = E.OBJECTID1
     AND D.OBJECTID2 = E.OBJECTID2
     AND  E.OBJECTVALUE1 = B.PNLNAME
           AND D.PROJECTNAME =  A.PROJECTNAME);
           
           
/* FIELDS IN THE PROJECT THAT ARE NOT IN PAGES IN THE PROJECT */
SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME LIKE 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' FROM 
  PSPNLFIELD C, PSPROJECTITEM D
  WHERE  D.OBJECTTYPE = 5
     AND C.PNLNAME = D.OBJECTVALUE1
     AND B.FIELDNAME = C.FIELDNAME 
     AND A.PROJECTNAME = D.PROJECTNAME);
     
     
/* FIELDS IN THE PROJECT THAT ARE NOT IN RECORDS IN THE PROJECT */
     SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' FROM 
  PSRECFIELD C, PSPROJECTITEM D
  WHERE  D.OBJECTTYPE = 0
     AND C.SUBRECORD = 'N'
     AND C.RECNAME = D.OBJECTVALUE1
     AND B.FIELDNAME = C.FIELDNAME
     AND A.PROJECTNAME = D.PROJECTNAME);
    
 /* FIELDS IN THE PROJECT THAT ARE NOT IN RECORDS IN THE DATABASE */
     SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' FROM 
  PSRECFIELD C
     WHERE B.FIELDNAME = C.FIELDNAME);   
    
    
/* FIELDS IN THE PROJECT THAT ARE NOT IN THE DATABASE */
     SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME like 'CY2_CONFIG_001' 
   AND NOT EXISTS(SELECT 'X' FROM PSDBFIELD C WHERE B.FIELDNAME = C.FIELDNAME);
   
   
           /* FIELDS IN THE PROJECT THAT ARE NOT IN RECORDS IN THE PROJECT */
     SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' FROM 
  PSRECFIELD C, PSPROJECTITEM D
  WHERE  D.OBJECTTYPE = 0
     AND C.SUBRECORD = 'N'
     AND C.RECNAME = D.OBJECTVALUE1
     AND B.FIELDNAME = C.FIELDNAME
     AND A.PROJECTNAME = D.PROJECTNAME);
     
     
       /* RECORD FIELDS IN THE PROJECT THAT ARE NOT AS FIELDS IN THE PROJECT */
     SELECT DISTINCT A.PROJECTNAME, B.RECNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSRECFIELD B
  WHERE  A.OBJECTTYPE = 0
     AND A.OBJECTVALUE1 = B.RECNAME
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' 
  FROM PSPROJECTITEM D, PSDBFIELD C
  WHERE D.OBJECTTYPE = 2
     AND D.OBJECTVALUE1 = C.FIELDNAME
     AND D.OBJECTID2 = 0
     AND B.FIELDNAME = C.FIELDNAME
    AND A.PROJECTNAME = D.PROJECTNAME);
    
    
    
    /* record fields that are not on pages in the project */
      SELECT DISTINCT A.PROJECTNAME, B.RECNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSRECFIELD B
  WHERE  A.OBJECTTYPE = 0
     AND A.OBJECTVALUE1 = B.RECNAME
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
     AND B.SUBRECORD <> 'Y'
      AND NOT EXISTS(SELECT 'X' FROM 
  PSPNLFIELD C, PSPROJECTITEM D
  WHERE  D.OBJECTTYPE = 5
     AND C.PNLNAME = D.OBJECTVALUE1
     AND B.FIELDNAME = C.FIELDNAME 
     AND A.PROJECTNAME = D.PROJECTNAME);
     
     
     /* Panel fields not in the project */
SELECT distinct d.PROJECTNAME, C.PNLNAME, C.FIELDNAME FROM 
  PSPNLFIELD C, PSPROJECTITEM D, PSDBFIELD E
  WHERE  D.OBJECTTYPE = 5
     AND C.PNLNAME = D.OBJECTVALUE1 
     AND C.FIELDNAME <> ' '
     AND C.FIELDNAME = E.FIELDNAME
     AND E.LASTUPDOPRID <> 'PPLSOFT'
        AND D.PROJECTNAME like 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' 
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND B.FIELDNAME = C.FIELDNAME
    AND A.PROJECTNAME = D.PROJECTNAME);
    
    /* RECORD FIELDS IN THE PROJECT THAT ARE NOT AS FIELDS IN THE PROJECT */
     SELECT DISTINCT A.PROJECTNAME, B.RECNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSRECFIELD B, PSDBFIELD C
  WHERE  A.OBJECTTYPE = 0
     AND A.OBJECTVALUE1 = B.RECNAME
     AND A.PROJECTNAME LIKE 'CY2_CONFIG_001' 
     AND B.FIELDNAME = C.FIELDNAME
     AND C.LASTUPDOPRID <> 'PPLSOFT'
     AND NOT EXISTS(SELECT 'X' 
  FROM PSPROJECTITEM D, PSDBFIELD E
  WHERE D.OBJECTTYPE = 2
     AND D.OBJECTVALUE1 = E.FIELDNAME
     AND D.OBJECTID2 = 0
     AND B.FIELDNAME = E.FIELDNAME
    AND A.PROJECTNAME = D.PROJECTNAME);
    
    
          /* FIELDS IN THE PROJECT THAT ARE NOT IN RECORDS IN THE PROJECT */
     SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME LIKE 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' FROM 
  PSRECFIELD C, PSPROJECTITEM D
  WHERE  D.OBJECTTYPE = 0
     AND C.SUBRECORD = 'N'
     AND C.RECNAME = D.OBJECTVALUE1
     AND B.FIELDNAME = C.FIELDNAME
     AND A.PROJECTNAME = D.PROJECTNAME);
     

/* SQL IN PEOPLECODE IN PROJECT, NOT IN SQLDEFN TABLE */     
     SELECT DISTINCT B.REFNAME, A.OBJECTVALUE1, A.OBJECTVALUE2, A.OBJECTVALUE3, A.OBJECTVALUE4
  FROM PSPROJECTITEM A, PSPCMNAME B
  WHERE A.OBJECTVALUE1 = B.OBJECTVALUE1
     AND A.OBJECTVALUE2 = B.OBJECTVALUE2
     AND ( A.OBJECTVALUE3 = B.OBJECTVALUE3
     OR A.OBJECTVALUE3 = ' ')
     AND ( A.OBJECTVALUE4 = B.OBJECTVALUE4
     OR A.OBJECTVALUE4 = ' ')
     AND A.OBJECTID1 = B.OBJECTID1
     AND A.OBJECTID2 = B.OBJECTID2
     AND ( A.OBJECTID3 = B.OBJECTID3
     OR A.OBJECTID3 = 0)
     AND ( A.OBJECTID4 = B.OBJECTID4
     OR A.OBJECTID4 = 0)
   AND B.RECNAME= 'SQL'
   AND A.PROJECTNAME = 'CY2_CONFIG_001'
   AND NOT EXISTS(SELECT 'X' FROM PSSQLTEXTDEFN C WHERE B.REFNAME = C.SQLID);
     
     /* STAND ALONE SQL IN PROJECT BUT NOT USED IN PEOPLECODE IN PROJECT */
SELECT A.PROJECTNAME, A.OBJECTVALUE1
  FROM PSPROJECTITEM A
  WHERE A.OBJECTTYPE = 30
     AND A.OBJECTID1 = 65
     AND A.OBJECTVALUE2 = 0
   AND A.PROJECTNAME LIKE 'CY2_CONFIG_001'
     AND NOT EXISTS(SELECT 'X'
  FROM PSPROJECTITEM B, PSPCMNAME C
  WHERE C.REFNAME = A.OBJECTVALUE1
  AND B.PROJECTNAME =  A.PROJECTNAME
 AND B.OBJECTVALUE1 = C.OBJECTVALUE1
     AND B.OBJECTVALUE2 = C.OBJECTVALUE2
     AND ( B.OBJECTVALUE3 = C.OBJECTVALUE3
     OR B.OBJECTVALUE3 = ' ')
     AND ( B.OBJECTVALUE4 = C.OBJECTVALUE4
     OR B.OBJECTVALUE4 = ' ')
     AND B.OBJECTID1 = C.OBJECTID1
     AND B.OBJECTID2 = C.OBJECTID2
     AND ( B.OBJECTID3 = C.OBJECTID3
     OR B.OBJECTID3 = 0)
     AND ( B.OBJECTID4 = C.OBJECTID4
     OR B.OBJECTID4 = 0)
   AND C.RECNAME= 'SQL');
   
   /* SQL STATEMENTS REFERENCED IN PEOPLECODE BUT MISSING FROM THE PROJECT */
SELECT DISTINCT A.PROJECTNAME, B.REFNAME, A.OBJECTVALUE1, A.OBJECTVALUE2, A.OBJECTVALUE3, A.OBJECTVALUE4
  FROM PSPROJECTITEM A, PSPCMNAME B
  WHERE A.OBJECTVALUE1 = B.OBJECTVALUE1
     AND A.OBJECTVALUE2 = B.OBJECTVALUE2
     AND ( A.OBJECTVALUE3 = B.OBJECTVALUE3
     OR A.OBJECTVALUE3 = ' ')
     AND ( A.OBJECTVALUE4 = B.OBJECTVALUE4
     OR A.OBJECTVALUE4 = ' ')
     AND A.OBJECTID1 = B.OBJECTID1
     AND A.OBJECTID2 = B.OBJECTID2
     AND ( A.OBJECTID3 = B.OBJECTID3
     OR A.OBJECTID3 = 0)
     AND ( A.OBJECTID4 = B.OBJECTID4
     OR A.OBJECTID4 = 0)
   AND B.RECNAME= 'SQL'
   AND A.PROJECTNAME LIKE 'CY2_CONFIG_001'
   and not exists(SELECT 'X'
  FROM PSPROJECTITEM C
  WHERE C.OBJECTTYPE = 30
     AND C.OBJECTID1 = 65
     AND C.OBJECTVALUE2 = 0
     AND C.OBJECTVALUE1 = B.REFNAME
    AND C.PROJECTNAME =  A.PROJECTNAME);

 /* MISSING RECORDS VIEWS IN PROJECT  */
     SELECT A.PROJECTNAME, B.RECNAME
  FROM PSPROJECTITEM A, PSRECDEFN B
  WHERE  A.OBJECTTYPE = 0
     AND A.OBJECTVALUE1 = B.RECNAME
     AND B.RECTYPE = 1
     AND A.PROJECTNAME LIKE 'CY2_CONFIG_001' 
     and not exists(SELECT 'X'
  FROM PSPROJECTITEM C
  WHERE C.OBJECTTYPE = 30
     AND C.OBJECTID1 = 65
     AND C.OBJECTVALUE2 = 2
     AND C.OBJECTVALUE1 = B.RECNAME
    AND C.PROJECTNAME =  A.PROJECTNAME);
     
     
new ideas: 
- translate values that do not exist in fields in the project
- translate values that do not exist in the database

 
 
 
 /* FIELDS IN THE PROJECT THAT ARE NOT IN RECORDS IN THE DATABASE */
     SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME = 'CY2_LOGIN_001' 
     AND NOT EXISTS(SELECT 'X' FROM 
  PSRECFIELD C
     WHERE B.FIELDNAME = C.FIELDNAME);   
     
     
     
         /* RECORD FIELDS IN THE PROJECT THAT ARE NOT AS FIELDS IN THE PROJECT */
     SELECT DISTINCT A.PROJECTNAME, B.RECNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSRECFIELD B, PSDBFIELD C
  WHERE  A.OBJECTTYPE = 0
     AND A.OBJECTVALUE1 = B.RECNAME
     AND A.PROJECTNAME LIKE 'CY2_LOGIN_001' 
     AND B.FIELDNAME = C.FIELDNAME
     AND C.LASTUPDOPRID <> 'PPLSOFT'
     AND NOT EXISTS(SELECT 'X' 
  FROM PSPROJECTITEM D, PSDBFIELD E
  WHERE D.OBJECTTYPE = 2
     AND D.OBJECTVALUE1 = E.FIELDNAME
     AND D.OBJECTID2 = 0
     AND B.FIELDNAME = E.FIELDNAME
    AND A.PROJECTNAME = D.PROJECTNAME);

SELECT * FROM PSPROJECTITEM WHERE PROJECTNAME LIKE 'CY2_CONFIG_001' AND OBJECTTYPE = 0 
SELECT * FROM PScontdefn WHERE PROJECTNAME LIKE 'CY2_CONFIG_001' AND OBJECTTYPE = 0 



     /* records in the project that are not in the database */
      SELECT DISTINCT A.PROJECTNAME, A.OBJECTVALUE1
  FROM PSPROJECTITEM A
  WHERE  A.OBJECTTYPE = 0
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' FROM psrecdefn B WHERE B.RECNAME = A.OBJECTVALUE1);
     
         /* FIELDS IN THE PROJECT THAT ARE NOT IN THE DATABASE */
     SELECT A.PROJECTNAME, A.OBJECTVALUE1
  FROM PSPROJECTITEM A
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
   AND NOT EXISTS(SELECT 'X' FROM PSDBFIELD B WHERE B.FIELDNAME = A.OBJECTVALUE1);


/* SQL STATEMENTS REFERENCED IN PEOPLECODE BUT MISSING FROM THE PROJECT */
SELECT DISTINCT A.PROJECTNAME, B.REFNAME, A.OBJECTVALUE1, A.OBJECTVALUE2, A.OBJECTVALUE3, A.OBJECTVALUE4
  FROM PSPROJECTITEM A, PSPCMNAME B
  WHERE A.OBJECTVALUE1 = B.OBJECTVALUE1
     AND A.OBJECTVALUE2 = B.OBJECTVALUE2
     AND ( A.OBJECTVALUE3 = B.OBJECTVALUE3
     OR A.OBJECTVALUE3 = ' ')
     AND ( A.OBJECTVALUE4 = B.OBJECTVALUE4
     OR A.OBJECTVALUE4 = ' ')
     AND A.OBJECTID1 = B.OBJECTID1
     AND A.OBJECTID2 = B.OBJECTID2
     AND ( A.OBJECTID3 = B.OBJECTID3
     OR A.OBJECTID3 = 0)
     AND ( A.OBJECTID4 = B.OBJECTID4
     OR A.OBJECTID4 = 0)
   AND B.RECNAME= 'SQL'
   AND A.PROJECTNAME LIKE 'CY2%'
   and not exists(SELECT 'X'
  FROM PSPROJECTITEM C
  WHERE C.OBJECTTYPE = 30
     AND C.OBJECTID1 = 65
     AND C.OBJECTVALUE1 = B.REFNAME
    AND C.PROJECTNAME =  A.PROJECTNAME);

/* Fluid style classes for page fields */
select A.PNLNAME, A.RECNAME, A.FIELDNAME, A.FIELDNUM, B.ffstylelong  from pspnlfielD A
, pspnlfieldEXT B WHERE B.ffstylelong not like ' | | | | ' AND B.ffstylelong not like ' '
AND A.PNLNAME = B.PNLNAME 
AND A.PNLFLDID = B.PNLFLDID
AND EXISTS(
SELECT 'X' FROM 
PSPROJECTITEM C
  WHERE  C.OBJECTTYPE = 5
     AND A.PNLNAME = C.OBJECTVALUE1
        AND C.PROJECTNAME = 'CY2_LOGIN_001');
        
        
/* Fluid style classes for pages */
select A.PNLNAME, A.FFSTYLEDESKTOP, A.FFSTYLEPHONE, A.FFSTYLETABLET, A.FFSTYLEMEDIUM, A.FFSTYLEEXLARGE 
from PSPNLDEFN A WHERE 
(A.FFSTYLEDESKTOP <> ' ' OR 
A.FFSTYLEPHONE  <> ' ' OR A.FFSTYLETABLET  <> ' ' OR A.FFSTYLEMEDIUM  <> ' ' OR  A.FFSTYLEEXLARGE  <> ' ')
AND EXISTS(
SELECT 'X' FROM 
PSPROJECTITEM B
  WHERE  B.OBJECTTYPE = 5
     AND A.PNLNAME = B.OBJECTVALUE1
        AND B.PROJECTNAME = 'CY2_LOGIN_001');

/* page peoplecodes without matching page in project */
SELECT A.PROJECTNAME, C.PNLNAME, B.PCTEXT
  FROM PSPROJECTITEM A, PSPCMTXT B,  PSPNLDEFN C
  WHERE A.OBJECTTYPE = 44
     AND A.OBJECTVALUE1 = B.OBJECTVALUE1
     AND A.OBJECTVALUE2 = B.OBJECTVALUE2
     AND B.OBJECTID1 = A.OBJECTID1
     AND B.OBJECTID2 = A.OBJECTID2
     AND B.OBJECTVALUE1 = C.PNLNAME
     AND A.PROJECTNAME LIKE 'CY2%'
     AND NOT EXISTS(SELECT 'X'
  FROM PSPROJECTITEM D, PSPNLDEFN E
  WHERE D.OBJECTTYPE = 5
     AND E.PNLNAME = D.OBJECTVALUE1
     AND E.PNLNAME = C.PNLNAME
    AND D.PROJECTNAME =  A.PROJECTNAME);
           
/* pages with missing page peoplecode in project */
SELECT A.PROJECTNAME, B.PNLNAME, C.PCTEXT
FROM PSPROJECTITEM A, PSPNLDEFN B, PSPCMTXT C
  WHERE  A.OBJECTTYPE = 5
     AND B.PNLNAME = A.OBJECTVALUE1
     AND B.PNLNAME = C.OBJECTVALUE1
     AND C.OBJECTID1 = 9
        AND A.PROJECTNAME LIKE 'CY2%'
  AND NOT EXISTS(SELECT 'X'
  FROM PSPROJECTITEM D, PSPCMTXT E
  WHERE D.OBJECTTYPE = 44
     AND D.OBJECTVALUE1 = E.OBJECTVALUE1
     AND D.OBJECTVALUE2 = E.OBJECTVALUE2
     AND D.OBJECTID1 = E.OBJECTID1
     AND D.OBJECTID2 = E.OBJECTID2
     AND  E.OBJECTVALUE1 = B.PNLNAME
           AND D.PROJECTNAME =  A.PROJECTNAME);
           
           
/* FIELDS IN THE PROJECT THAT ARE NOT IN PAGES IN THE PROJECT */
SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME LIKE 'CY2_CONFIG%' 
     AND NOT EXISTS(SELECT 'X' FROM 
  PSPNLFIELD C, PSPROJECTITEM D
  WHERE  D.OBJECTTYPE = 5
     AND C.PNLNAME = D.OBJECTVALUE1
     AND B.FIELDNAME = C.FIELDNAME 
     AND A.PROJECTNAME = D.PROJECTNAME);
     
     
             /* FIELDS IN THE PROJECT THAT ARE NOT IN RECORDS IN THE PROJECT */
     SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' FROM 
  PSRECFIELD C, PSPROJECTITEM D
  WHERE  D.OBJECTTYPE = 0
     AND C.SUBRECORD = 'N'
     AND C.RECNAME = D.OBJECTVALUE1
     AND B.FIELDNAME = C.FIELDNAME
     AND A.PROJECTNAME = D.PROJECTNAME);
    
    
/* FIELDS IN THE PROJECT THAT ARE NOT IN THE DATABASE */
     SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME like 'CY2_%' 
   AND NOT EXISTS(SELECT 'X' FROM PSDBFIELD C WHERE B.FIELDNAME = C.FIELDNAME);
   
   
           /* FIELDS IN THE PROJECT THAT ARE NOT IN RECORDS IN THE PROJECT */
     SELECT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSDBFIELD B
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTVALUE1 = B.FIELDNAME
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' FROM 
  PSRECFIELD C, PSPROJECTITEM D
  WHERE  D.OBJECTTYPE = 0
     AND C.SUBRECORD = 'N'
     AND C.RECNAME = D.OBJECTVALUE1
     AND B.FIELDNAME = C.FIELDNAME
     AND A.PROJECTNAME = D.PROJECTNAME);
     
     
       /* RECORD FIELDS IN THE PROJECT THAT ARE NOT AS FIELDS IN THE PROJECT */
     SELECT DISTINCT A.PROJECTNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSRECFIELD B
  WHERE  A.OBJECTTYPE = 0
     AND A.OBJECTVALUE1 = B.RECNAME
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
     AND NOT EXISTS(SELECT 'X' 
  FROM PSPROJECTITEM D, PSDBFIELD C
  WHERE D.OBJECTTYPE = 2
     AND D.OBJECTVALUE1 = C.FIELDNAME
     AND D.OBJECTID2 = 0
     AND B.FIELDNAME = C.FIELDNAME
    AND A.PROJECTNAME = D.PROJECTNAME);
    
    
    
    /* record fields that are not on pages in the project */
      SELECT DISTINCT A.PROJECTNAME, B.RECNAME, B.FIELDNAME
  FROM PSPROJECTITEM A, PSRECFIELD B
  WHERE  A.OBJECTTYPE = 0
     AND A.OBJECTVALUE1 = B.RECNAME
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
      AND NOT EXISTS(SELECT 'X' FROM 
  PSPNLFIELD C, PSPROJECTITEM D
  WHERE  D.OBJECTTYPE = 5
     AND C.PNLNAME = D.OBJECTVALUE1
     AND B.FIELDNAME = C.FIELDNAME 
     AND A.PROJECTNAME = D.PROJECTNAME);
     
     
 /* MESSAGE CATALOG ENTRIES IN PAGE FIELDS THE PROJECT */
 SELECT c.projectname, A.PNLNAME, A.GRDLBLMSGSET, A.GRDLBLMSGnum
  FROM PSPNLFIELD A, PSPNLDEFN B, PSPROJECTITEM C
  WHERE  A.PNLNAME = B.PNLNAME
     AND A.PNLNAME = C.OBJECTVALUE1
     AND C.OBJECTTYPE = 5
      AND C.PROJECTNAME = 'CY2_LOG_16'
  AND A.GRDLBLMSGSET > 0;
  