    /* FIELDS IN THE PROJECT THAT ARE NOT IN THE DATABASE */
     SELECT A.PROJECTNAME, A.OBJECTVALUE1
  FROM PSPROJECTITEM A
  WHERE  A.OBJECTTYPE = 2
     AND A.OBJECTID2 = 0
     AND A.PROJECTNAME = 'CY2_CONFIG_001' 
   AND NOT EXISTS(SELECT 'X' FROM PSDBFIELD B WHERE B.FIELDNAME = A.OBJECTVALUE1);
