/* MISSING DEFAULT RECORDS FOR RECORD FIELDS IN PROJECT  */
  SELECT B.RECNAME, B.DEFRECNAME
  FROM PSPROJECTITEM A, PSRECFIELD B, PSRECDEFN E
  WHERE  A.OBJECTTYPE = 0
     AND A.OBJECTVALUE1 = B.RECNAME
     AND A.PROJECTNAME = 'CY2_AD_APPL_001' 
     AND B.DEFRECNAME <> ' '
     AND B.DEFRECNAME = E.RECNAME
     AND E.LASTUPDOPRID <> 'PPLSOFT'
     AND NOT EXISTS(SELECT 'X' FROM 
  PSRECDEFN C, PSPROJECTITEM D
  WHERE D.OBJECTTYPE = 0
     AND C.RECNAME = D.OBJECTVALUE1
     AND C.RECNAME = B.DEFRECNAME
     AND A.PROJECTNAME = D.PROJECTNAME);