/* MISSING PROMPT RECORDS IN PROJECT  */
     SELECT B.RECNAME, B.EDITTABLE
  FROM PSPROJECTITEM A, PSRECFIELD B, PSRECDEFN E
  WHERE  A.OBJECTTYPE = 0
     AND A.OBJECTVALUE1 = B.RECNAME
     AND A.PROJECTNAME = 'CY2_AD_APPL_001' 
     AND B.EDITTABLE <> ' '
     AND B.EDITTABLE = E.RECNAME
     AND E.LASTUPDOPRID <> 'PPLSOFT'
     AND NOT EXISTS(SELECT 'X' FROM 
  PSRECDEFN C, PSPROJECTITEM D
  WHERE D.OBJECTTYPE = 0
     AND C.RECNAME = D.OBJECTVALUE1
     AND C.RECNAME = B.EDITTABLE
     AND A.PROJECTNAME = D.PROJECTNAME);