 /* MISSING RELATED LANGUAGE RECORDS IN PROJECT  */
     SELECT B.RECNAME, B.RELLANGRECNAME
  FROM PSPROJECTITEM A, PSRECDEFN B
  WHERE  A.OBJECTTYPE = 0
     AND A.OBJECTVALUE1 = B.RECNAME
     AND A.PROJECTNAME = 'CY2_AD_APPL_001' 
     AND B.RELLANGRECNAME <> ' '
     AND NOT EXISTS(SELECT 'X' FROM 
  PSRECDEFN C, PSPROJECTITEM D
  WHERE D.OBJECTTYPE = 0
     AND C.RECNAME = D.OBJECTVALUE1
     AND C.RECNAME = B.RELLANGRECNAME
     AND A.PROJECTNAME = D.PROJECTNAME);