 /* MESSAGE CATALOG ENTRIES IN PAGE FIELDS THE PROJECT */
 SELECT c.projectname, A.PNLNAME, A.GRDLBLMSGSET, A.GRDLBLMSGnum
  FROM PSPNLFIELD A, PSPNLDEFN B, PSPROJECTITEM C
  WHERE  A.PNLNAME = B.PNLNAME
     AND A.PNLNAME = C.OBJECTVALUE1
     AND C.OBJECTTYPE = 5
      AND C.PROJECTNAME = 'CY2_LOG_16'
  AND A.GRDLBLMSGSET > 0;