SELECT A.PROJECTNAME, B.PNLGRPNAME, B.DESCR
FROM PSPROJECTITEM A,
  PSPNLGRPDEFN B
WHERE B.PNLGRPNAME = A.OBJECTVALUE1
AND B.MARKET         = A.OBJECTVALUE2
AND A.OBJECTTYPE     = 7
----AND A.PROJECTNAME = 'XXXXXXXXXXXX'
AND NOT EXISTS(SELECT 'X' FROM PSPROJECTITEM C, PSPRSMDEFN D
  WHERE C.OBJECTTYPE = 55
     AND C.OBJECTID1 = 99
     AND C.OBJECTVALUE1 = D.PORTAL_NAME
     AND C.OBJECTID2 = 100
     AND C.OBJECTVALUE2 = D.PORTAL_REFTYPE
     AND C.OBJECTID3 = 101
     AND C.OBJECTVALUE3 = D.PORTAL_OBJNAME
     AND A.PROJECTNAME = C.PROJECTNAME
AND B.PNLGRPNAME = D.PORTAL_URI_SEG2)