/* page peoplecodes without matching page in project */
SELECT A.PROJECTNAME, C.PNLNAME, B.PCTEXT
  FROM PSPROJECTITEM A, PSPCMTXT B,  PSPNLDEFN C
  WHERE A.OBJECTTYPE = 44
     AND A.OBJECTVALUE1 = B.OBJECTVALUE1
     AND A.OBJECTVALUE2 = B.OBJECTVALUE2
     AND B.OBJECTID1 = A.OBJECTID1
     AND B.OBJECTID2 = A.OBJECTID2
     AND B.OBJECTVALUE1 = C.PNLNAME
     AND A.PROJECTNAME = 'CY2_LOGIN_001'
     AND NOT EXISTS(SELECT 'X'
  FROM PSPROJECTITEM D, PSPNLDEFN E
  WHERE D.OBJECTTYPE = 5
     AND E.PNLNAME = D.OBJECTVALUE1
     AND E.PNLNAME = C.PNLNAME
    AND D.PROJECTNAME =  A.PROJECTNAME);