/* pages with missing page peoplecode in project */
SELECT A.PROJECTNAME, B.PNLNAME, C.PCTEXT
FROM PSPROJECTITEM A, PSPNLDEFN B, PSPCMTXT C
  WHERE  A.OBJECTTYPE = 5
     AND B.PNLNAME = A.OBJECTVALUE1
     AND B.PNLNAME = C.OBJECTVALUE1
     AND C.OBJECTID1 = 9
        AND A.PROJECTNAME = 'CY2_LOGIN_001'
  AND NOT EXISTS(SELECT 'X'
  FROM PSPROJECTITEM D, PSPCMTXT E
  WHERE D.OBJECTTYPE = 44
     AND D.OBJECTVALUE1 = E.OBJECTVALUE1
     AND D.OBJECTVALUE2 = E.OBJECTVALUE2
     AND D.OBJECTID1 = E.OBJECTID1
     AND D.OBJECTID2 = E.OBJECTID2
     AND  E.OBJECTVALUE1 = B.PNLNAME
           AND D.PROJECTNAME =  A.PROJECTNAME);